# -*- coding: utf-8 -*-
"""Number Guessing Game

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mLr-3Lzf7LnzwW4_4ue7ROutzSLy--d_
"""

import random

def play_game(max_number, max_times):

    number = random.randint(1, max_number)
    count = 0

    print("Guess a number between 1 and", max_number)

    while count < max_times:
        guess = int(input("Your guess: "))
        count += 1

        if guess == number:
            print("Yes, you got it right, you used", count, "times")
            return
        elif guess > number:
            print("Too big")
        else:
            print("Too small")

    print("Game over, number was", number)
while True:

    print("\n-----New Game-----")

    level = input("1 Easy  2 Normal  3 Hard  0 Quit ")

    if level == "1":
        play_game(50, 10)

    elif level == "2":
        play_game(100, 7)

    elif level == "3":
        play_game(200, 5)

    elif level == "0":
        break

    else:
        print("Wrong input")