# -*- coding: utf-8 -*-
"""Number Guessing Game

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mLr-3Lzf7LnzwW4_4ue7ROutzSLy--d_
"""

import random

number = random.randint(1, 100)
count = 0

print("Guess a number between 1 and 100")

while True:
    guess = int(input("Your guess: "))
    count += 1

    if guess == number:
        print("Yes, you got it right!")
        print("You guessed", count, "times.")
        break
    elif guess > number:
        print("Too big")
    else:
        print("Too small")